name: g-synth
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - biopython>=1.79
  - pandas>=1.5.0
  - pip
  - pip:
    - ttkbootstrap>=1.10.1
    - dna-features-viewer>=3.1.0
    - streamlit>=1.28.0
    - plotly>=5.15.0